# Generated by Django 3.2 on 2021-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0002_itemlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
