# Generated by Django 3.2 on 2021-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0004_remove_category_c_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='image',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='c_image_url',
            field=models.URLField(null=True),
        ),
    ]
