# Generated by Django 3.2 on 2021-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantiy',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
