# Generated by Django 3.2 on 2021-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0009_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='c_image_url',
            new_name='image_url',
        ),
    ]
