# Generated by Django 3.2 on 2021-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0010_rename_c_image_url_itemlist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
