# Generated by Django 3.2 on 2021-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanagement', '0011_alter_category_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='calory',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
