# Generated by Django 3.2 on 2021-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
