# Generated by Django 3.2 on 2021-05-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210511_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_option',
            field=models.CharField(choices=[('0', 'Cash on delivery'), ('1', 'Credit Card')], default=0, max_length=40, null=True),
        ),
    ]
