# Generated by Django 3.2 on 2021-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
